import createClient from 'openapi-fetch';
import type { paths } from './types'; // generated by openapi-typescript

export const client = createClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_API_URL,
});
